### ISSUE TITLE
conflict in peft

### ISSUE THREAD

**Issue by slefforgeENERCALC** [taprosoft/llm_finetuning#6]
requirements.txt has `git+https://github.com/huggingface/peft.git`

cuda_quant_requirements.txt has `peft==0.4.0`

when I try and install both of these, I see the following

```
Collecting git+https://github.com/huggingface/peft.git (from -r requirements.txt (line 1))
  Cloning https://github.com/huggingface/peft.git to /tmp/pip-req-build-n5akfjww
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-req-build-n5akfjww
  Resolved https://github.com/huggingface/peft.git to commit ad8f7cb59ee7ca4b9ca1c9048711038ac36b31b8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Cannot install peft 0.11.2.dev0 (from git+https://github.com/huggingface/peft.git) and peft==0.4.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested peft 0.11.2.dev0 (from git+https://github.com/huggingface/peft.git)
    The user requested peft==0.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by slefforgeENERCALC** [comment]
additionally, if I just leave everything as is, this is what the Colab workaround says

```quant_cuda not found. Please run "pip install alpaca_lora_4bit[cuda]".
Replaced attention with xformers_attention
Traceback (most recent call last):
  File "/content/llm_finetuning/finetune.py", line 441, in <module>
    fire.Fire(train)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/llm_finetuning/finetune.py", line 288, in train
    model, tokenizer = load_model_gptq(
  File "/content/llm_finetuning/utils/loader/gptq_loader.py", line 50, in load_model_gptq
    autograd_4bit.switch_backend_to("cuda")
  File "/usr/local/lib/python3.10/dist-packages/alpaca_lora_4bit/autograd_4bit.py", line 139, in switch_backend_to
    raise ValueError('quant_cuda not found. Please reinstall with pip install .')
ValueError: quant_cuda not found. Please reinstall with pip install .```
